### PR TITLE
Build and publish packages automatically via Travis CI

### PR DESCRIPTION
**Pull request by rmax**
This PR adds a travis configuration to build and publish packages automatically to Scrapinghub's anaconda.org channel. It includes Scrapy 1.0.3 and related dependencies not available in conda by default.

### CODE REVIEW

**Comment by rmax** [comment]
This fixes #2.

**Comment by dangra** [comment]
hi @rolando, I don't think we need travis-ci to build conda packages. Scrapinghub is paying for anaconda service so we can use their builders for all platforms for free.

According to docs it is possible to trigger binstar builds directly from github http://docs.anaconda.org/draft/examples.html#SubmitABuildFromGithub an it mentions there is support for `--sub-dir`

**Comment by rmax** [comment]
@dangra yes, anaconda.org provides one linux-64 free builder, and as a paid organization account, we have one additional worker **slot** where we can attach our own workers.

Each worke can build only packages for one platform, so if we want to support all available platforms (or at least osx-64 and win-64) we will need to purchase additional worker slots.

I tried to do this workaround of building the package and then converting them but was not possible in a straightforward manner, it seems the system is hardcoded to upload only the package built for the platform defined by the worker. Hence I opted to try travis instead.

**Comment by pablohoffman** [comment]
We can always add more workers, the main thing (for me) is to make sure we have the process automated enough to be done on all releases.

**Comment by rmax** [comment]
@pablohoffman OK. I will set up the automatic builds in anaconda.org.

**Comment by dangra** [comment]
>  OK. I will set up the automatic builds in anaconda.org.
>  Show all checks

:+1:

**Pull request merged**
